<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise</title>
</head>

<body>
    <script>
        const promise = new Promise((resolve, reject) => {
            //resolve(10);
            //console.log('resolve和reject任意执行后, promise状态已改, 后续[resolve, reject]不执行')
            resolve({ success: true });
            // reject(new Error('出错了!'));

        });

        // 调用方式1
        // promise.then((data) => {
        //     console.log('data:', data);
        // }, (err) => {
        //     console.log('err:', err);
        // });

        // 调用方式2
        // promise.then((data) => {
        //     console.log('data:', data);
        // }).catch(err => {
        //     console.log('err:', err);
        // });

        // 调用方式3 async/await


        // example
        const sucessUrl = 'https://api.randomuser.me/?nat=US&results=1';
        const failUrl = 'http://api.openweathermap.org/data/2.5/weather?q=London&units=Metric&APIkey=c36b03a963176b9a639859e6cf279299http://openweathermap.org/img/w/10n.png';
        function ajax(url) {
            return new Promise((resolve, reject) => {
                const xhr = new XMLHttpRequest();
                xhr.open('GET', url);
                xhr.responseType = 'json';
                xhr.onload = function () {
                    if (this.status === 200) {
                        resolve(this.response);
                    } else {
                        reject(new Error(this.statusText));
                    }
                }
                xhr.send();
            });
        }

        ajax(sucessUrl).then(res => console.log('res:', res)).catch(err => console.log('err:', err))
        ajax(failUrl).then(res => console.log('res:', res)).catch(err => console.log('err:', err))
    </script>
</body>

</html>